### ISSUE TITLE
[Learn] foo의 의미는?

### ISSUE THREAD

**Issue by SoheeP** [Hello-Programing/Same-Refo#6]
## 질문
+ 사람들이 foo를 많이 쓰던데 도대체 이 foo가 뭔가요?

## 스크린샷
![Cap 2019-03-11 15-50-03-415](https://user-images.githubusercontent.com/43696483/54105091-5904ce80-4415-11e9-90e4-db89aed4d3f2.png)

**Comment by Phantom05** [comment]
>foo란 Lorem같이 의미 없는 단어로 사용됩니다!.

\- by @Phantom05
\- contact : [monster2jy@gmail.com](monster2jy@gmail.com)
